# Generated by Django 4.1.1 on 2022-10-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cc',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
