# Generated by Django 4.1.1 on 2022-10-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('animal', '0002_animal_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
            preserve_default=False,
        ),
    ]
